### ISSUE TITLE
toHaveStyle throws error for jest config

### ISSUE THREAD

**Issue by dojchek** [NetanelBasal/spectator#497]
### Is this a regression?

Yes

### Description

toHaveStyle matcher fails when using jest. Setup is quite simple:
```
import { createComponentFactory, Spectator } from '@ngneat/spectator/jest';
import { Component } from '@angular/core';

@Component({
  selector: 'cdg-test',
  template: `<span style="color: indianred;"></span>`,
})
export class TestComponent {}

describe('TestComponent', () => {
  let spectator: Spectator<TestComponent>;
  const createComponent = createComponentFactory({ component: TestComponent });
  beforeEach(() => (spectator = createComponent()));

  it('should have style', () => {
    // Arrange
    const color = 'indianred';
    // Act
    spectator.detectChanges();
    const spanElement = spectator.query('span');
    // Assert
    expect(spanElement).toHaveStyle({ color });
  });
});
```

The test works if the style is extracted 'manually' and matched with `toEqual` like showed in the following snippet:
```
it('should have style', () => {
    // ... 
    // Assert
    const style = spanElement.getAttribute('style');
    expect(style).toEqual(`color: ${color};`);
  });
```

### Please provide the exception or error you saw

```true
computed.getPropertyValue is not a function
TypeError: computed.getPropertyValue is not a function
    at curCSS (C:\dev\repos\cdgweb\node_modules\jquery\dist\jquery.js:6591:18)
    at Function.css (C:\dev\repos\cdgweb\node_modules\jquery\dist\jquery.js:6996:10)
    at C:\dev\repos\cdgweb\node_modules\jquery\dist\jquery.js:7145:12
    at access (C:\dev\repos\cdgweb\node_modules\jquery\dist\jquery.js:4203:15)
    at jQuery.fn.init.css (C:\dev\repos\cdgweb\node_modules\jquery\dist\jquery.js:7127:10)
    at hasCss (C:\dev\repos\cdgweb\node_modules\projects\spectator\src\lib\matchers.ts:68:20)
    at Object.ɵ16 (C:\dev\repos\cdgweb\node_modules\projects\spectator\src\lib\matchers.ts:295:16)
    at __EXTERNAL_MATCHER_TRAP__ (C:\dev\repos\cdgweb\node_modules\expect\build\index.js:386:30)
    at Object.throwingMatcher [as toHaveStyle] (C:\dev\repos\cdgweb\node_modules\expect\build\index.js:387:15)
    at C:\dev\repos\cdgweb\src\app\SCAM\components\color-picker\color-picker.component.spec.ts:53:33
    at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (C:\dev\repos\cdgweb\node_modules\zone.js\dist\zone.js:386:30)
    at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (C:\dev\repos\cdgweb\node_modules\zone.js\dist\proxy.js:117:43)
    at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (C:\dev\repos\cdgweb\node_modules\zone.js\dist\zone.js:385:36)
    at Zone.Object.<anonymous>.Zone.run (C:\dev\repos\cdgweb\node_modules\zone.js\dist\zone.js:143:47)
    at Object.wrappedFunc (C:\dev\repos\cdgweb\node_modules\jest-preset-angular\build\zone-patch\index.js:36:30)
    at Promise.then.completed (C:\dev\repos\cdgweb\node_modules\jest-circus\build\utils.js:390:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\dev\repos\cdgweb\node_modules\jest-circus\build\utils.js:315:10)
    at _callCircusTest (C:\dev\repos\cdgweb\node_modules\jest-circus\build\run.js:218:40)
    at _runTest (C:\dev\repos\cdgweb\node_modules\jest-circus\build\run.js:155:3)
    at _runTestsForDescribeBlock (C:\dev\repos\cdgweb\node_modules\jest-circus\build\run.js:66:9)
    at _runTestsForDescribeBlock (C:\dev\repos\cdgweb\node_modules\jest-circus\build\run.js:60:9)
    at _runTestsForDescribeBlock (C:\dev\repos\cdgweb\node_modules\jest-circus\build\run.js:60:9)
    at run (C:\dev\repos\cdgweb\node_modules\jest-circus\build\run.js:25:3)
    at runAndTransformResultsToJestFormat (C:\dev\repos\cdgweb\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:167:21)
```

### Please provide the environment you discovered this bug in
@ngneat/spectator: 8.1.0

### Do you want to create a pull request?

No

**Comment by matheo** [comment]
This is still an issue in the latest `v8.3.1` 
we had to downgrade to `v8.2.0`
